trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  TF_VERSION: "1.9.8"

steps:
  - script: |
      wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
      unzip terraform_$(TF_VERSION)_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform version
    displayName: "Install Terraform"

  - task: AzureCLI@2
    displayName: "Terraform Init"
    inputs:
      azureSubscription: "terraform-azure-sp"
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      workingDirectory: "$(System.DefaultWorkingDirectory)"
      inlineScript: |
        terraform init -input=false

  - script: |
      terraform fmt -check -recursive
    displayName: "Terraform Format Check"
    workingDirectory: "$(System.DefaultWorkingDirectory)"

  - script: |
      terraform validate
    displayName: "Terraform Validate"
    workingDirectory: "$(System.DefaultWorkingDirectory)"

  - task: AzureCLI@2
    displayName: "Terraform Plan"
    inputs:
      azureSubscription: "terraform-azure-sp"
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      workingDirectory: "$(System.DefaultWorkingDirectory)"
      inlineScript: |
        terraform plan -input=false -var-file="environments/prod.tfvars"
