trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      echo "Installing Terraform..."
      wget https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      unzip terraform_1.9.8_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform version
    displayName: "Install Terraform"

  - task: AzureCLI@2
    displayName: "Terraform Init"
    inputs:
    azureSubscription: "new azure connectionn"
    addSpnToEnvironment: true
    scriptType: "bash"
    scriptLocation: "inlineScript"
    inlineScript: |
      export ARM_USE_OIDC=true
      export ARM_USE_AZUREAD=true
      terraform init

  - script: terraform validate
    displayName: "Terraform Validate"

  - task: AzureCLI@2
    displayName: "Terraform Plan"
    inputs:
    azureSubscription: "new azure connectionn"
    addSpnToEnvironment: true
    scriptType: "bash"
    scriptLocation: "inlineScript"
    inlineScript: |
      export ARM_USE_OIDC=true
      export ARM_USE_AZUREAD=true
      terraform plan -var-file="environments/prod.tfvars"
